/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.uat.ui.internal.UatActivator;

public class AcceptanceTestUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return UatActivator.getInstance().getInjector("org.xtext.example.mydsl.AcceptanceTest");
	}

}
