/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.acceptanceTest;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.acceptanceTest.AcceptanceTestFactory
 * @model kind="package"
 * @generated
 */
public interface AcceptanceTestPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "acceptanceTest";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/AcceptanceTest";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "acceptanceTest";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AcceptanceTestPackage eINSTANCE = org.xtext.example.mydsl.acceptanceTest.impl.AcceptanceTestPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.acceptanceTest.impl.AcceptanceTestImpl <em>Acceptance Test</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.acceptanceTest.impl.AcceptanceTestImpl
   * @see org.xtext.example.mydsl.acceptanceTest.impl.AcceptanceTestPackageImpl#getAcceptanceTest()
   * @generated
   */
  int ACCEPTANCE_TEST = 0;

  /**
   * The feature id for the '<em><b>Tests</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACCEPTANCE_TEST__TESTS = 0;

  /**
   * The number of structural features of the '<em>Acceptance Test</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACCEPTANCE_TEST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.acceptanceTest.impl.ItemImpl <em>Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.acceptanceTest.impl.ItemImpl
   * @see org.xtext.example.mydsl.acceptanceTest.impl.AcceptanceTestPackageImpl#getItem()
   * @generated
   */
  int ITEM = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM__NAME = 0;

  /**
   * The feature id for the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM__QUANTITY = 1;

  /**
   * The number of structural features of the '<em>Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.acceptanceTest.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.acceptanceTest.impl.ActionImpl
   * @see org.xtext.example.mydsl.acceptanceTest.impl.AcceptanceTestPackageImpl#getAction()
   * @generated
   */
  int ACTION = 2;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__ACTION = 0;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.acceptanceTest.impl.CaseImpl <em>Case</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.acceptanceTest.impl.CaseImpl
   * @see org.xtext.example.mydsl.acceptanceTest.impl.AcceptanceTestPackageImpl#getCase()
   * @generated
   */
  int CASE = 3;

  /**
   * The feature id for the '<em><b>Items</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE__ITEMS = 0;

  /**
   * The number of structural features of the '<em>Case</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CASE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.acceptanceTest.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.acceptanceTest.impl.ConditionImpl
   * @see org.xtext.example.mydsl.acceptanceTest.impl.AcceptanceTestPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 4;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__ACTION = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__VALUE = 1;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.acceptanceTest.impl.OutcomeImpl <em>Outcome</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.acceptanceTest.impl.OutcomeImpl
   * @see org.xtext.example.mydsl.acceptanceTest.impl.AcceptanceTestPackageImpl#getOutcome()
   * @generated
   */
  int OUTCOME = 5;

  /**
   * The feature id for the '<em><b>Items</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTCOME__ITEMS = 0;

  /**
   * The feature id for the '<em><b>Result</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTCOME__RESULT = 1;

  /**
   * The number of structural features of the '<em>Outcome</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTCOME_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.acceptanceTest.impl.TestCaseImpl <em>Test Case</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.acceptanceTest.impl.TestCaseImpl
   * @see org.xtext.example.mydsl.acceptanceTest.impl.AcceptanceTestPackageImpl#getTestCase()
   * @generated
   */
  int TEST_CASE = 6;

  /**
   * The feature id for the '<em><b>Given</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE__GIVEN = 0;

  /**
   * The feature id for the '<em><b>When</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE__WHEN = 1;

  /**
   * The feature id for the '<em><b>Then</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE__THEN = 2;

  /**
   * The number of structural features of the '<em>Test Case</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_CASE_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.acceptanceTest.AcceptanceTest <em>Acceptance Test</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Acceptance Test</em>'.
   * @see org.xtext.example.mydsl.acceptanceTest.AcceptanceTest
   * @generated
   */
  EClass getAcceptanceTest();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.acceptanceTest.AcceptanceTest#getTests <em>Tests</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tests</em>'.
   * @see org.xtext.example.mydsl.acceptanceTest.AcceptanceTest#getTests()
   * @see #getAcceptanceTest()
   * @generated
   */
  EReference getAcceptanceTest_Tests();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.acceptanceTest.Item <em>Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Item</em>'.
   * @see org.xtext.example.mydsl.acceptanceTest.Item
   * @generated
   */
  EClass getItem();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.acceptanceTest.Item#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.acceptanceTest.Item#getName()
   * @see #getItem()
   * @generated
   */
  EAttribute getItem_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.acceptanceTest.Item#getQuantity <em>Quantity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Quantity</em>'.
   * @see org.xtext.example.mydsl.acceptanceTest.Item#getQuantity()
   * @see #getItem()
   * @generated
   */
  EAttribute getItem_Quantity();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.acceptanceTest.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see org.xtext.example.mydsl.acceptanceTest.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.acceptanceTest.Action#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action</em>'.
   * @see org.xtext.example.mydsl.acceptanceTest.Action#getAction()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Action();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.acceptanceTest.Case <em>Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Case</em>'.
   * @see org.xtext.example.mydsl.acceptanceTest.Case
   * @generated
   */
  EClass getCase();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.acceptanceTest.Case#getItems <em>Items</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Items</em>'.
   * @see org.xtext.example.mydsl.acceptanceTest.Case#getItems()
   * @see #getCase()
   * @generated
   */
  EReference getCase_Items();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.acceptanceTest.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see org.xtext.example.mydsl.acceptanceTest.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.acceptanceTest.Condition#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Action</em>'.
   * @see org.xtext.example.mydsl.acceptanceTest.Condition#getAction()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_Action();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.acceptanceTest.Condition#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.acceptanceTest.Condition#getValue()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.acceptanceTest.Outcome <em>Outcome</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Outcome</em>'.
   * @see org.xtext.example.mydsl.acceptanceTest.Outcome
   * @generated
   */
  EClass getOutcome();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.acceptanceTest.Outcome#getItems <em>Items</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Items</em>'.
   * @see org.xtext.example.mydsl.acceptanceTest.Outcome#getItems()
   * @see #getOutcome()
   * @generated
   */
  EReference getOutcome_Items();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.acceptanceTest.Outcome#getResult <em>Result</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Result</em>'.
   * @see org.xtext.example.mydsl.acceptanceTest.Outcome#getResult()
   * @see #getOutcome()
   * @generated
   */
  EAttribute getOutcome_Result();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.acceptanceTest.TestCase <em>Test Case</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test Case</em>'.
   * @see org.xtext.example.mydsl.acceptanceTest.TestCase
   * @generated
   */
  EClass getTestCase();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.acceptanceTest.TestCase#getGiven <em>Given</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Given</em>'.
   * @see org.xtext.example.mydsl.acceptanceTest.TestCase#getGiven()
   * @see #getTestCase()
   * @generated
   */
  EReference getTestCase_Given();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.acceptanceTest.TestCase#getWhen <em>When</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>When</em>'.
   * @see org.xtext.example.mydsl.acceptanceTest.TestCase#getWhen()
   * @see #getTestCase()
   * @generated
   */
  EReference getTestCase_When();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.acceptanceTest.TestCase#getThen <em>Then</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Then</em>'.
   * @see org.xtext.example.mydsl.acceptanceTest.TestCase#getThen()
   * @see #getTestCase()
   * @generated
   */
  EReference getTestCase_Then();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AcceptanceTestFactory getAcceptanceTestFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.acceptanceTest.impl.AcceptanceTestImpl <em>Acceptance Test</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.acceptanceTest.impl.AcceptanceTestImpl
     * @see org.xtext.example.mydsl.acceptanceTest.impl.AcceptanceTestPackageImpl#getAcceptanceTest()
     * @generated
     */
    EClass ACCEPTANCE_TEST = eINSTANCE.getAcceptanceTest();

    /**
     * The meta object literal for the '<em><b>Tests</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACCEPTANCE_TEST__TESTS = eINSTANCE.getAcceptanceTest_Tests();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.acceptanceTest.impl.ItemImpl <em>Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.acceptanceTest.impl.ItemImpl
     * @see org.xtext.example.mydsl.acceptanceTest.impl.AcceptanceTestPackageImpl#getItem()
     * @generated
     */
    EClass ITEM = eINSTANCE.getItem();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ITEM__NAME = eINSTANCE.getItem_Name();

    /**
     * The meta object literal for the '<em><b>Quantity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ITEM__QUANTITY = eINSTANCE.getItem_Quantity();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.acceptanceTest.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.acceptanceTest.impl.ActionImpl
     * @see org.xtext.example.mydsl.acceptanceTest.impl.AcceptanceTestPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__ACTION = eINSTANCE.getAction_Action();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.acceptanceTest.impl.CaseImpl <em>Case</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.acceptanceTest.impl.CaseImpl
     * @see org.xtext.example.mydsl.acceptanceTest.impl.AcceptanceTestPackageImpl#getCase()
     * @generated
     */
    EClass CASE = eINSTANCE.getCase();

    /**
     * The meta object literal for the '<em><b>Items</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CASE__ITEMS = eINSTANCE.getCase_Items();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.acceptanceTest.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.acceptanceTest.impl.ConditionImpl
     * @see org.xtext.example.mydsl.acceptanceTest.impl.AcceptanceTestPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__ACTION = eINSTANCE.getCondition_Action();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__VALUE = eINSTANCE.getCondition_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.acceptanceTest.impl.OutcomeImpl <em>Outcome</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.acceptanceTest.impl.OutcomeImpl
     * @see org.xtext.example.mydsl.acceptanceTest.impl.AcceptanceTestPackageImpl#getOutcome()
     * @generated
     */
    EClass OUTCOME = eINSTANCE.getOutcome();

    /**
     * The meta object literal for the '<em><b>Items</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OUTCOME__ITEMS = eINSTANCE.getOutcome_Items();

    /**
     * The meta object literal for the '<em><b>Result</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTCOME__RESULT = eINSTANCE.getOutcome_Result();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.acceptanceTest.impl.TestCaseImpl <em>Test Case</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.acceptanceTest.impl.TestCaseImpl
     * @see org.xtext.example.mydsl.acceptanceTest.impl.AcceptanceTestPackageImpl#getTestCase()
     * @generated
     */
    EClass TEST_CASE = eINSTANCE.getTestCase();

    /**
     * The meta object literal for the '<em><b>Given</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_CASE__GIVEN = eINSTANCE.getTestCase_Given();

    /**
     * The meta object literal for the '<em><b>When</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_CASE__WHEN = eINSTANCE.getTestCase_When();

    /**
     * The meta object literal for the '<em><b>Then</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST_CASE__THEN = eINSTANCE.getTestCase_Then();

  }

} //AcceptanceTestPackage
