/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.acceptanceTest;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Acceptance Test</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.acceptanceTest.AcceptanceTest#getTests <em>Tests</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.acceptanceTest.AcceptanceTestPackage#getAcceptanceTest()
 * @model
 * @generated
 */
public interface AcceptanceTest extends EObject
{
  /**
   * Returns the value of the '<em><b>Tests</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.acceptanceTest.TestCase}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tests</em>' containment reference list.
   * @see org.xtext.example.mydsl.acceptanceTest.AcceptanceTestPackage#getAcceptanceTest_Tests()
   * @model containment="true"
   * @generated
   */
  EList<TestCase> getTests();

} // AcceptanceTest
