/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.acceptanceTest;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Outcome</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.acceptanceTest.Outcome#getItems <em>Items</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.acceptanceTest.Outcome#getResult <em>Result</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.acceptanceTest.AcceptanceTestPackage#getOutcome()
 * @model
 * @generated
 */
public interface Outcome extends EObject
{
  /**
   * Returns the value of the '<em><b>Items</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.acceptanceTest.Item}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items</em>' containment reference list.
   * @see org.xtext.example.mydsl.acceptanceTest.AcceptanceTestPackage#getOutcome_Items()
   * @model containment="true"
   * @generated
   */
  EList<Item> getItems();

  /**
   * Returns the value of the '<em><b>Result</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Result</em>' attribute.
   * @see #setResult(String)
   * @see org.xtext.example.mydsl.acceptanceTest.AcceptanceTestPackage#getOutcome_Result()
   * @model
   * @generated
   */
  String getResult();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.acceptanceTest.Outcome#getResult <em>Result</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Result</em>' attribute.
   * @see #getResult()
   * @generated
   */
  void setResult(String value);

} // Outcome
