/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.acceptanceTest;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test Case</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.acceptanceTest.TestCase#getGiven <em>Given</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.acceptanceTest.TestCase#getWhen <em>When</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.acceptanceTest.TestCase#getThen <em>Then</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.acceptanceTest.AcceptanceTestPackage#getTestCase()
 * @model
 * @generated
 */
public interface TestCase extends EObject
{
  /**
   * Returns the value of the '<em><b>Given</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Given</em>' reference.
   * @see #setGiven(Case)
   * @see org.xtext.example.mydsl.acceptanceTest.AcceptanceTestPackage#getTestCase_Given()
   * @model
   * @generated
   */
  Case getGiven();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.acceptanceTest.TestCase#getGiven <em>Given</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Given</em>' reference.
   * @see #getGiven()
   * @generated
   */
  void setGiven(Case value);

  /**
   * Returns the value of the '<em><b>When</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>When</em>' reference.
   * @see #setWhen(Condition)
   * @see org.xtext.example.mydsl.acceptanceTest.AcceptanceTestPackage#getTestCase_When()
   * @model
   * @generated
   */
  Condition getWhen();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.acceptanceTest.TestCase#getWhen <em>When</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>When</em>' reference.
   * @see #getWhen()
   * @generated
   */
  void setWhen(Condition value);

  /**
   * Returns the value of the '<em><b>Then</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then</em>' reference.
   * @see #setThen(Outcome)
   * @see org.xtext.example.mydsl.acceptanceTest.AcceptanceTestPackage#getTestCase_Then()
   * @model
   * @generated
   */
  Outcome getThen();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.acceptanceTest.TestCase#getThen <em>Then</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then</em>' reference.
   * @see #getThen()
   * @generated
   */
  void setThen(Outcome value);

} // TestCase
