/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalAcceptanceTestParser;
import org.xtext.example.mydsl.services.AcceptanceTestGrammarAccess;

public class AcceptanceTestParser extends AbstractAntlrParser {

	@Inject
	private AcceptanceTestGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAcceptanceTestParser createParser(XtextTokenStream stream) {
		return new InternalAcceptanceTestParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "AcceptanceTest";
	}

	public AcceptanceTestGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AcceptanceTestGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
