/*
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.AcceptanceTestRuntimeModule;
import org.xtext.example.mydsl.AcceptanceTestStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AcceptanceTestIdeSetup extends AcceptanceTestStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AcceptanceTestRuntimeModule(), new AcceptanceTestIdeModule()));
	}
	
}
